export const employees = [
  {
    id: 1,
    first_name: "Matthieu",
    last_name: "Giraud-Heraud",
    date_birthday: "24/07/1992",
    start_date: "07/11/2021",
    street: "41 Rue des Vénitiens",
    city: "Limoges",
    state: "FR",
    zip_code: 87000,
    department: "Sales",
  },
  {
    id: 2,
    first_name: "Charlene",
    last_name: "Faucheux",
    date_birthday: "20/11/1993",
    start_date: "09/01/2018",
    street: "10 Rue Homme de fer",
    city: "Strasbourg",
    state: "FR",
    zip_code: 67000,
    department: "Engenring",
  },
  {
    id: 3,
    first_name: "Fabien",
    last_name: "Roux",
    date_birthday: "18/10/2003",
    start_date: "29/06/2020",
    street: "58 Avenue de la Libération",
    city: "Amiens",
    state: "FR",
    zip_code: 12000,
    department: "Customers",
  },
  {
    id: 4,
    first_name: "Vincent",
    last_name: "Dubois",
    date_birthday: "19/08/2000",
    start_date: "14/08/2005",
    street: "10 Rue de La Poste",
    city: "Alabama",
    state: "AL",
    zip_code: 59520,
    department: "Marketing",
  },
  {
    id: 5,
    first_name: "Alice",
    last_name: "Poirier",
    date_birthday: "11/01/1988",
    start_date: "24/04/2001",
    street: "1 Ter le Lapin",
    city: "Rennes",
    state: "GA",
    zip_code: 64120,
    department: "Human Ressources",
  },
  {
    id: 6,
    first_name: "Anthony",
    last_name: "Choin",
    date_birthday: "18/12/1970",
    start_date: "27/07/1992",
    street: "18 rue de la Coiffeuse",
    city: "Paris",
    state: "ME",
    zip_code: 67000,
    department: "Legal",
  },
  {
    id: 7,
    first_name: "Eric",
    last_name: "Junior",
    date_birthday: "28/09/1978",
    start_date: "22/05/1990",
    street: "67 Avenue de Paris",
    city: "Rennes",
    state: "ME",
    zip_code: 25200,
    department: "Legal",
  },
  {
    id: 8,
    first_name: "Vincent",
    last_name: "Dubois",
    date_birthday: "19/08/2000",
    start_date: "14/08/2005",
    street: "10 Rue de La Poste",
    city: "Alabama",
    state: "AL",
    zip_code: 59520,
    department: "Marketing",
  },
  {
    id: 9,
    first_name: "Alice",
    last_name: "Poirier",
    date_birthday: "11/01/1988",
    start_date: "24/04/2001",
    street: "1 Ter le Lapin",
    city: "Rennes",
    state: "GA",
    zip_code: 64120,
    department: "Human Ressources",
  },
  {
    id: 10,
    first_name: "Anthony",
    last_name: "Choin",
    date_birthday: "18/12/1970",
    start_date: "27/07/1992",
    street: "18 rue de la Coiffeuse",
    city: "Paris",
    state: "ME",
    zip_code: 67000,
    department: "Legal",
  },
  {
    id: 11,
    first_name: "Eric",
    last_name: "Junior",
    date_birthday: "28/09/1978",
    start_date: "22/05/1990",
    street: "67 Avenue de Paris",
    city: "Rennes",
    state: "ME",
    zip_code: 25200,
    department: "Legal",
  },
];
